platform:
- x86
environment:
  global:
    FORK_USER: ocaml
    FORK_BRANCH: master
    CYG_ROOT: C:\cygwin64
    PINS: eqaf:.
  matrix:
  - OPAM_SWITCH: 4.03.0+mingw64c
    PACKAGE: eqaf
  - OPAM_SWITCH: 4.03.0+mingw32c
    PACKAGE: eqaf
  - OPAM_SWITCH: 4.04.2+mingw64c
    PACKAGE: eqaf
  - OPAM_SWITCH: 4.04.2+mingw32c
    PACKAGE: eqaf
  - OPAM_SWITCH: 4.05.0+mingw64c
    PACKAGE: eqaf
  - OPAM_SWITCH: 4.05.0+mingw32c
    PACKAGE: eqaf
  - OPAM_SWITCH: 4.06.0+mingw64c
    PACKAGE: eqaf
  - OPAM_SWITCH: 4.06.0+mingw32c
    PACKAGE: eqaf
install:
- curl -L -o nasminst.exe https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-installer-x86.exe
- start /wait nasminst.exe /S
- ps: $env:path="C:\Program Files (x86)\nasm;$($env:path)"
- ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))
build_script:
- call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
