language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PINS="mirage-crypto.dev:. mirage-crypto-rng.dev:. mirage-crypto-pk.dev:. mirage-crypto-entropy.dev:."
    - PACKAGE="mirage-crypto-pk"
    - TESTS=true
matrix:
  include:
  - os: osx
    env: OCAML_VERSION=4.08
  - dist: xenial
    env: OCAML_VERSION=4.08 DEPOPTS="zarith-xen mirage-xen-posix"
notifications:
  email: false
