language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="io-page.dev:."
  matrix:
  - DISTRO="debian-stable" OCAML_VERSION=4.04 PACKAGE="io-page"
  - DISTRO="alpine"        OCAML_VERSION=4.06 PACKAGE="io-page"
  - DISTRO="alpine"        OCAML_VERSION=4.07 PACKAGE="io-page"
  - DISTRO="alpine"        OCAML_VERSION=4.08 PACKAGE="io-page"
