language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="xenstore_transport"
  - PINS="xenstore_transport:. xenstore-tool:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="xenstore_transport" OCAML_VERSION="4.04"
  - PACKAGE="xenstore-tool"      OCAML_VERSION="4.04"
  - PACKAGE="xenstore_transport" OCAML_VERSION="4.07"
  - PACKAGE="xenstore-tool"      OCAML_VERSION="4.07"
