language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml
  - $HOME/.opam

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build

# Please keep the list in sync with the minimal version of OCaml in
# dune-project, dune.opam.template and bootstrap.ml

matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.02 OCAML_RELEASE=3 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.07 OCAML_RELEASE=1 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.08 OCAML_RELEASE=1 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.09 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.09 OCAML_RELEASE=0 WITH_OPAM=1
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
  - os: osx
    env: OCAML_VERSION=4.09 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build_macOS
