# AppVeyor config using https://github.com/Chris00/ocaml-appveyor

install:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - install_ocaml.cmd

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - ocaml bootstrap.ml
  - dune.exe build @test\blackbox-tests\windows-diff

artifacts:
  - path: _build/log
    name: build-log
  - path: _boot/log
    name: build_bootstrap-log

# Uncomment this to enable Remote Desktop on the build worker at the end of the
# build. The worker is available for the remainder of the allocated hour.
# on_finish:
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
